#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🙂 Please be patient, this may take sometime...⏳'

echo '👷🏻⚒️ Styling your code before committing...'
yarn format-write

echo '👮🏻🔎 Checking Styles in your code before committing...'
yarn format-check

echo '👮🏻🚨 Making sure no linting errors in your code before committing...'
yarn lint ||
(

    echo '⚠️ Oops❗, you have a problem in your code. Check linter ❌⚒️
          💡Run yarn lint, add changes & try committing again.👍🏻';
    false;
)

echo '👮🏻🚨 Making sure no typescript errors in your code before committing...'
yarn type-check ||
(

    echo '⚠️ Oops❗, you have a type error in your code. Check types ❌⚒️
          💡Run yarn type-check, add changes & try committing again.👍🏻';
    false;
)

echo '🎉 All checks passed ✅, committing your code...✨🚀🏄‍♂️🍻'