name: Main Pipeline
run-name: ${{ github.actor }} triggered the Main Pipeline 🚀
on:
  push:
    branches: [main]
jobs:
  Main-Pipeline:
    uses: ./.github/workflows/deployment-jobs.yml
    permissions:
      id-token: write
      contents: read
    with:
      ref: ${{ github.ref }}
      artifact-rep: ${{ vars['ARTIFACT_REPO_PROD'] }}
      run-service-name: 'portfolio-prod'
    secrets:
      wif-provider: ${{ secrets['WIF_PROVIDER_PROD'] }}
      wif-sa: ${{ secrets['WIF_SA_PROD'] }}
